### PR TITLE
Xero Tap

### PR DESCRIPTION
**Pull request by b-ryan**
QA Notes:

- Runtime for demo account sync of all data from 2001: 10.753s
- Total records sent to Stitch: 630
- Total rows replicated by Stitch: 2189

Using the singer-check-tap command, I confirmed that no rows were replicated during the second run except for the streams that sync all rows every time.

- Second run records sent to Stitch: 22
- Total rows replicated by Stitch: 2232

I sanity checked the schemas within Redshift. The only oddity I noticed was that "date" fields had a string datatype in Redshift. Is this expected? "date-time" fields were fine.

### CODE REVIEW

**Comment by cmerrick** [comment]
> The only oddity I noticed was that "date" fields had a string datatype in Redshift. Is this expected? "date-time" fields were fine.

`date-time` is a special format that is defined by the [JSON Schema Spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3), and we translate these values into redshift timestamps.  Just `date` is not defined by the JSON Schema Spec, so we don't have any special handling for it. 

I think that our schema validator will accept and correctly handle a `date-time` formatted like `2017-07-01`, although this is a bit of a loose interpretation of rfc3339.  If not, then I think we should add a `T00:00:00Z` to the end of the date string and use the `date-time` format.

**Comment by mdelaurentis** [comment]
@b-ryan @cmerrick I think I mentioned this in the Google Doc, but should we consider using an NTP server to get time rather than using the clock on our own server or from the HTTP headers? We can't eliminate clock skew on Xero's side, but at least we can use a consistent time on our side.

**Comment by b-ryan** [comment]
I think you can't do much better than using the time their servers are giving us. The NTP server would be consistent, but I would at least expect the timestamp they put on their responses to generally drift with the updated timestamp on their objects.

In any case you can't protect against this entirely. Even using the "updated at" timestamps on the objects can suffer from the same issue. I think the only way to entirely protect against it would be to subtract some amount of time whenever updating the bookmark. This applies to all taps though, not just Xero.

**Comment by cmerrick** [comment]
We discussed this internally - we actually removed the wallclock-dependent code in the hubspot tap in order to improve correctness, and we're reluctant to use it here.  Here's how I think we should handle each of the 4 endpoints where ModifiedAt isn't clear:
 - `bank_transfers`: this appears to be an append-only endpoint, so use the `CreatedDateUTC` as the bookmark
 - `repeating_invoices`: get full data set every time
 - `tax_rates`: get full data set every time
 - `tracking_categories`: get full data set every time

**Pull request merged**
